### PR TITLE
[WIP] vis-rotation

### PR DESCRIPTION
**Pull request by bobbraswell**
A function which interactively rotates two factors relative to each other while continuously updating a plot of the results.

### CODE REVIEW

**Comment by maxheld83** [comment]
uh this is great news @bobbraswell – I actually have a very similar function in the works in #97. Let's compare notes and maybe combine the best of both?
I'll look at this in the next 1-3 days and report back here.

**Comment by maxheld83** [comment]
also, @bobbraswell, if you're curious about my prior work / thoughts about this, consider all the [issues tagged rotation](https://github.com/aiorazabala/qmethod/issues?q=is%3Aopen+is%3Aissue+label%3Arotation) and especially this original issue #13 which also links to all relevant commits I've made in the past two months or so.

I've so far used the manual rotation function from the `psych` package, but I recently changed course and implemented it the matrix rotation myself.

It'll be exciting if we have this ready to go in Ancona! Any chance you'll also be in Ancona @bobbraswell ?

**Comment by bobbraswell** [comment]
I am new to Github and apparently didn't dig deeply enough to see your work
on this -- from what I had seen, judgmental rotation was not listed under
visualizations, and it seemed to be stuck on the to-do list. If I had known
how much work you had done on this, I probably would not have spent time on
it.  However, the upside is existence of an independent approach that may
add something.

I will be in Ancona and am looking forward to meeting you both.

**Comment by maxheld83** [comment]
It's great to have you on here @bobbraswell – welcome to GitHub and `qmethod`.
I think I can speak for @aiorazabala and myself that we're both excited to have an experienced Q-methodologist and list contributor as you join this effort.

Took me a while to get the hang of GitHub, too :smirk:, but I've learned to appreciate it.

It's generally a good idea to always go through the existing issues, or at least open a new issue, so that everyone is in the loop and to avoid duplicate efforts.

I have to apologise, though, (also to @aiorazabala) for making my PR #97 so huge and touching on so many things; that's bad style and confusing to people. 
Smaller, more nuclear PRs are preferable.
I can see how it was impossible to see from the existing PRs that work on rotation was already being done.
I'll do better from now on.

I've also expanded/added our [Contributing Guidelines](https://github.com/aiorazabala/qmethod/blob/master/CONTRIBUTING.md), meant to make on-boarding smoother. 
(From now on, users will be pointed to these guidelines whenever they open an issue or PR).
There's also a bunch of GitHub resources in there, that you may find helpful @bobbraswell.
Hope I got it right – we obviously don't want to make it harder for people to contribute, just trying to make sure the process is as smooth as it can be for everyone.

Let me get back to you about our now twin :smile: manual rotation functions once I got my documentation in a presentable form @bobbraswell . 
I'm thinking about a way to wrap my (somewhat more complex) function around yours, so that people can both use a really straightforward function (yours), or a more "hand-holding" variant (mine) if they like, but there are a couple of roadblocks that I haven't figured out yet.

**Comment by maxheld83** [comment]
ok, I think I have finally finished my work on the manual rotation procedures in #97 and now have a pretty-well tested version.
There's also a pretty longish video on the function on YouTube: https://www.youtube.com/watch?v=fWWujBrCPCc

Over the course of developing these functions, I've come to a couple of conclusions on how -- I think -- manual rotation should be organised on a technical level.
As a result, I fear we may not need another approach to this, and I also don't see a possibility to unite the two.

Let me explain:

- I find it important that manual rotation can be *reproduced*, even if just for technical reasons (say, in a `*.Rnw`  script or something).
- The only feasible way to reproduce any given manual rotation (because the order matters aka matrix multiplication does not commutate) is **to save the rotation matrix**.

To that end, I have implemented two entirely separate functions:

1. `q.mrot.choose` let's you choose any pair of factors (much like the above) *in any order*, matrix multiplies into a rotation matrix (of rank == nfactors) and *preliminarily*  applies this matrix to the original loadings and calculates a completely new `results` object, with all the downstream statistics (that is needed for plots).
  Crucially, this function *does not return rotated loadings or results* (it returns nothing, in fact!), but **only writes the rotation matrix to a file**.
2. `q.mrot.do` then allows you to *read in that `rot.mat` file*  and to apply it to the original results (including their loadings), and to recompute all the downstream stuff.

Why the hassle?

So that when users have completed their manual rotation, they can always restore that manual rotation in future, in a programmatic way.
(This also allows target rotations and a bunch more future features, but that's not the issue now).

I think this has a couple of advantages over the above simpler function suggested by @bobbraswell:

- people can rotate *all* factor pairs "in one go", and in any order, they can go back and forth as much as they like
- the function is open to more informative plots such as `q.scoreplot`
- any results object will always *know* how it was created, namely, by `by-hand` rotation, and by its `rot.mat` which it continues to carry.

Again, I apologise for my part in failing to prevent this duplicate effort, and I hope this won't frustrate any further advances and contributions.

**Pull request closed without merging**
