### PR TITLE
make.distribution

### PR DESCRIPTION
**Pull request by maxheld83**
This is still **work in progress** on #4, and there's definitely still something wrong with this, just wanted to bring this up, so please no one ~~**merge this yet**~~.

I'm also starting with only the simple stuff, accepting only `nstats` and `max.bin` as variables.

I did it using `qnorm`, but I'm not even sure that makes sense.

Still, some scaffolding is in place.

### CODE REVIEW

**Comment by aiorazabala** [comment]
Please send the pull requests to dev, not to master

**Comment by maxheld83** [comment]
absolutely, sorry about that.
I'll put this up again for `dev`.
I've also updated #38 with that reminder (PR on `dev`!).

**Comment by maxheld83** [comment]
it occurs to me, this function is actually also ready for `1.3.0`.
@aiorazabala could you have a brief look at it and tell me if you think it's ready? I'll then merge it in.

**Comment by maxheld83** [comment]
we'll do this in 1.4.0. then

**Comment by maxheld83** [comment]
I think this is now ready.
I have:

- [x] Run `R CMD Check --as-cran` on
  - [x] OS X
  - [ ] Linux
  - [ ] Windows
- [x] proof-read on paper (hopefully got them all)
- [x] input verification
- [x] streamlined terminology with rest of docs

It's just a trivial helper function and **does not deserve a release on it's own**, but I'd love to wrap this into `master` just to get it out of the way.
Would you mind having a look at it @aiorazabala ?

**Comment by aiorazabala** [comment]
Hey, drop me an email when you'd like this to be merged

**Comment by aiorazabala** [comment]
Conflict resolved manually and updated

**Pull request merged**
